// G3.1 + G3.6: content store, embedded seed content, zip packs, uniqueness registry.
//
// Purpose: owns the runtime content/ tree (species/ water/ plants/ patterns/
// plus registry.json at the root): scan, validate, clamp, atomic write, seed,
// pack export/import and the C6 fingerprint uniqueness gate.
//
// Owns: internal/content/*.go and the embedded seed sources under
// internal/content/seed/** (go:embed; the runtime tree is generated by
// EnsureSeed at app start).
//
// Public API: Load; accessors Species/Plants/Waters/Recipes/SpeciesByID;
// Validate* (strict: slug ID, hex colors, enum values — never ranges);
// Write* (clamped copy, atomic tmp+rename, registry append); EnsureSeed;
// ExportPack/ImportPack; Gate (C6 uniqueness + case-insensitive name
// uniqueness) and GateRecipe for stage recipes; RecentFingerprints;
// HasID/HasName.
//
// Invariants: floats are clamped to README section 4 ranges on load and on
// write, never rejected; rejection only for unparseable JSON, bad hex, bad
// slug or bad enum, always with a log line and never a crash (D4); registry
// is append-only, deduped by hash, capped at contract.RegistryCap with the
// oldest entries dropped; every method is goroutine-safe.
//
// Extensions: a new artifact kind = new folder + decode case + seed files;
// fingerprint changes only touch the canonical builders in fingerprint.go.
package content
